### ISSUE TITLE
[v5] Sidebery is missing some shortcuts/functionality provided by Tree Style Tabs and its plugins.

### ISSUE THREAD

**Issue by drkhn1234** [mbnuqw/sidebery#1137]
Listed below are the shortcuts that either do exist in TST or one of its plugins that use TST's API, but not in Sidebery:

### Tree Style Tabs:
- [ ] Close this Tree
- [ ] Close Descendants
- [ ] Focus to Next Sibling Tab
- [ ] Focus to Previous Sibling Tab
- [ ] Focus to Last Child Tab
- [ ] Focus to First Child Tab
- [ ] Close Other Tabs except this Tree (We have close other tabs in Sidebery, but it doesn't exclude descendants of a tree from being closed while the shortcut is initiated at the root tab of a tree)
- [ ] Collapse this Tree Recursively (By default "Fold selected branch" shortcut collapses (i.e. folds) a tree and pertaining its descendant tabs' folded status whilst with this option/shortcut the achieved result would be folding of all descendants of a tree)
- [ ] Expand this Tree (Same logic as above, this conserves the folded structure of a tree's descendants; the desired result is to have any folded descendants of a tree switched to unfolded status)
- [ ] Expand All (Expand all folded tabs in a panel to unfolded status)
- [ ] Collapse All (same logic above, we currently have on Sidebery "Fold inactive branches", which is close enough to this in TST with the exception that it won't collapse the focused tree/branch)
- [ ] Move Current Tree Up (moves the tree/branch when its root is focused as whole through the list of tabs)
- [ ] Move Current Tree Down (vice versa above)

### TST More Tree Commands:
- [x] Toggle Collapsed State of Tree ( This is such a good feature that it is abhorrent we currently do not have this and have to bind two separate shortcuts to toggle folding of branches ): #1211, #1276
- [x] Flatten Tree ( There exists the functionality in Sidebery, it just needs a shortcut ): #1295
- [ ] Move Current Tab After Next Sibling ( Similar to "Move Current Tree Down" in Tree Style Tabs with the restriction that moving a tree/branch structure is only done at sibling level of the tree/branch's root tab, so that tree/branch cannot jump levels above/below than its current nested level)
- [ ] Move Current Tab Before Previous Sibling (vice versa above)

### TST Number Navigation:
- [ ] focus-parent-set-downstream ( This jumps to parent tab with the extra functionality over what we have on Sidebery that it sets a mark, called by the name "downstream", on a switched from tab that which can then later on be switched to by another shortcut this extension provides. Better try it yourself to fully grasp the functionality and its benefits )
- [ ] focus-downstream ( Switches to the marked child tab previously set below ("downstream") to a focused tree/branch, if there is no marked tab it switches to first child of tree/branch. While implementing this, providing an option to whether this shortcut goes to first child or the last, or which of the two depending on number of childs a tree/branch have, will be helpful to the user as it would help free up having to assign shortcuts to "Focus to Last Child Tab" & "Focus to First Child Tab". )
- [ ] focus-root-set-downstream (Focus to topmost parent (i.e. root of a tree, and set a mark on the switched from tab)
- [ ] focus-sibling-number-[1..n, last-tab] ( Sidebery provides many shortcuts for switching tabs by number, but I believe they are not very useful because 1) Firefox has native shortcuts for switching to tabs 1..8, last-tab & 2) Sidebery doesn't provide this behaviour scoped down to siblings, which is way useful than globally switching to nth tab as most likely one will have tabs more than 10 on global but probably likely less than 10 tabs on any given branch's childs.

**Comment by goodboy** [comment]
Definitely pertains to #616 in terms of a lacking inter-plugin API.

**Comment by BugZappr** [comment]
"Close Other Tabs except this Tree" is a great suggestion.  Other ones I miss from similar tree tab extensions are:

"Close Other Tabs except this"
"Close Tabs below this"
"Close Tabs above this"

A lot of the ideas in the OP are extensions not found en the original Tree Style Tabs.  Close to bottom and other than this are not only in the original, but especially useful.

**Comment by the-nelsonator** [comment]
@BugZappr 
> "Close Other Tabs except this"
> "Close Tabs below this"
> "Close Tabs above this"

All of these are in Sidebery's right click menu: 

![Image](https://github.com/user-attachments/assets/edaba73a-ec38-4887-b6cd-2e4125cd2fb3)

Is the ask for keyboard shortcuts?

**Comment by dlight** [comment]
> Is the ask for keyboard shortcuts?

Indeed it is!

Also,

> Close this Tree

There is a right click menu entry for this called "Close branch". Why isn't there a keyboard shortcut for that?
